group:
  - files:
      - source: raw_event_upcoming_earnings.csv
        dest: raw_event_upcoming_earnings.csv
      - source: raw_column_definition.md
        dest: definitions/raw_column_definition_InvestorEvents.md
    repos: |
      wenchiehlee-money/InvestorConference
  - files:
      - source: raw_event_historical_crashes.csv
        dest: raw_event_historical_crashes.csv
      - source: raw_column_definition.md
        dest: definitions/raw_column_definition_InvestorEvents.md
    repos: |
      wenchiehlee-money/VIX
